label:
  name: credit
  favorable_classes:
    - 1
protected_attributes:
  - name: sex
    privileged_classes:   # array or text(condition)
      - male
  - name: age
    # privileged_classes: "eval: x ${condition}"
    #                 ex) "eval: x = 10"
    #                     "eval: x >= 1
    #                     "eval: x != 0
    privileged_classes: "eval: x > 25"
categorical_features:
  - status
  - credit_history
  - purpose
  - savings
  - employment
  - other_debtors
  - property
  - installment_plans
  - housing
  - skill_level
  - telephone
  - foreign_worker
features_to_keep:
features_to_drop:
  - personal_status

# todo: use-case 고려하여 더 쉬운 방법 모색
custom_preprocessing: |-
  def custom_preprocessing(df):   # f: pd.DataFrame -> pd.DataFrame. default is None
      status_map = {'A91': 'male', 'A93': 'male', 'A94': 'male',
                    'A92': 'female', 'A95': 'female'}
      df['sex'] = df['personal_status'].replace(status_map)

      return df