# type = file|mysql|iris
#   type: file -> target: ${file_path}
#   type: mysql|iris -> target: ${table_name}
### * case1: file
#type: file
#target: ../sample_data/german.csv
### * case2: mysql
#type: mysql
#target: german
### * case3: iris
type: iris
target: test_data_german

# if type is file, db config is not necessary.
mysql:
  addr: 192.168.100.210
  port: 3306
  user: root
  password: pwd123
  database: fairness

iris:
  addr: 192.168.101.108
  user: fair
  password: "!cool@fairness#4"
  database: FAIR