# "privileged_groups" and "unprivileged_groups" must be disjoint.
privileged_groups:
  - age: 1
unprivileged_groups:
  - age: 0

metrics:
  - mean_difference
  - statistical_parity_difference
  - disparate_impact